const COUNTDOWN_INITIAL_NUMBER = 3;
const COUNTDOWN_FINAL_NUMBER = -1;

const WAIT_TIME_UNTIL_GAME_BEGIN_MILLISECONDS = 3000

module.exports = {
    COUNTDOWN_INITIAL_NUMBER,
    COUNTDOWN_FINAL_NUMBER,
    WAIT_TIME_UNTIL_GAME_BEGIN_MILLISECONDS
}
